version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9

    working_directory: /go/src/github.com/ninnemana/fuz

    steps:
      - checkout

      - run: go get
      - run: go test -v ./...
      