machine:
  environment:
    GOPATH: /home/ubuntu/.go_workspace
    IMPORT_PATH: github.com/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME

general:
  build_dir: ../.go_workspace/src/$IMPORT_PATH

checkout:
  post:
    - mkdir -p "$GOPATH/src/$IMPORT_PATH"
    - rsync -azC --delete $HOME/$CIRCLE_PROJECT_REPONAME/ $GOPATH/src/$IMPORT_PATH/

dependencies:
  pre:
    - go get -v -t -d ./...

test:
  override:
    - go test -v ./...

deployment:
  tag:
    tag: /v[0-9]+(\.[0-9]+)*(-.*)*/
    owner: user
    commands:
      - curl -sL https://git.io/goreleaser | bash
